# Generated by Django 5.1.1 on 2024-10-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.CharField(max_length=81)),
                ('solution', models.CharField(max_length=81)),
                ('player_progress', models.CharField(blank=True, max_length=81, null=True)),
            ],
        ),
    ]
