# Generated by Django 5.1.1 on 2024-10-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sudoku',
            new_name='SudokuGame',
        ),
    ]
